### ISSUE TITLE
Customize the share content based on destination

### ISSUE THREAD

**Issue by rodericj** [ThumbWorks/sf-ios#119]
When sharing (from the group view) we're sharing a string. Based on the destination we need to probably set the URL to nil.

See: `activitiyViewController itemForActivityType`

**Comment by jerrytdev** [comment]
The https://... becomes a link after it's sent so it should take the recipient directly to the App Store:  Download the Coffee Coffee Coffee app: https://itunes.apple.com/us/app/coffee-coffee-coffee/id1458031604?mt=8

**Comment by rodericj** [comment]
Only if there is a datadetector in the label displaying the content
