### ISSUE TITLE
App crashes when selecting WWDC Coffee

### ISSUE THREAD

**Issue by matthewspear** [ThumbWorks/sf-ios#129]
Steps to Reproduce:
- Build from source
- Install on device
- Launch app
- Click "WWDC Coffee" cell

Expected Results:
- Open list of events for WWDC

Actual Results:
- App crashes

Version/Build:
iOS 12.2
Build from source commit 5ae5d8

Stack Output:
[Output.txt](https://github.com/ThumbWorks/sf-ios/files/3229962/Output.txt)

**Comment by rodericj** [comment]
oh boy
