### ISSUE TITLE
Make map marker more prominent

### ISSUE THREAD

**Issue by ay8s** [ThumbWorks/sf-ios#51]
It kind of blends in against the other orange markers. 

![IMG_1912](https://user-images.githubusercontent.com/1058408/56635341-1809f780-661a-11e9-8d3e-51783c98b951.jpeg)

**Comment by rodericj** [comment]
~I've not played around with the annotations much but they look like stock `MKAnnotationView` objects.~ Looks like it's just an image asset. Should be pretty simple!
