### ISSUE TITLE
Notifications for when events are scheduled 

### ISSUE THREAD

**Issue by rodericj** [ThumbWorks/sf-ios#7]

**Comment by rodericj** [comment]
Continuing this from the server repo (https://github.com/jamescmartinez/coffee/issues/164): 

Realm, pincache, nsuserdefaults, coredata, disk serialization. What other options are there. I suppose it’s got to be queryable. Afaik that’s the biggest necessity

**Comment by jamescmartinez** [comment]
https://github.com/jamescmartinez/coffee/issues/164#issuecomment-480057015

**Comment by rodericj** [comment]
@jamescmartinez What are your thoughts on uniqueID for events? If you're not into it I could always hash based on group, and startDate. I could think of scenarios where this isn't appropriate though. It also makes deleting events or modifying start date of events darn near impossible.
